/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.labsemana2;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author telip
 */
public class dispatchWIN extends javax.swing.JFrame {
    PalindromoAir pa=sellWIN.pa;
    
    

    /**
     * Creates new form disposeWIN
     */
    public dispatchWIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        incomeLABEL.setText(Double.toString(pa.income()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disposeBUTT = new javax.swing.JButton();
        backBUTT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        incomeLABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        disposeBUTT.setBackground(new java.awt.Color(0, 0, 255));
        disposeBUTT.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        disposeBUTT.setForeground(new java.awt.Color(255, 255, 255));
        disposeBUTT.setText("Dispatch");
        disposeBUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeBUTTActionPerformed(evt);
            }
        });

        backBUTT.setBackground(new java.awt.Color(0, 0, 255));
        backBUTT.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        backBUTT.setForeground(new java.awt.Color(255, 255, 255));
        backBUTT.setText("Back");
        backBUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBUTTActionPerformed(evt);
            }
        });

        jLabel1.setText("Income:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(incomeLABEL))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBUTT)
                        .addGap(187, 187, 187)
                        .addComponent(disposeBUTT)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(incomeLABEL))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disposeBUTT)
                    .addComponent(backBUTT))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disposeBUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeBUTTActionPerformed
        pa.dispatch();
        Icon icon;
        JOptionPane.showMessageDialog(null, "El vuelo ha sido despachado!");
    }//GEN-LAST:event_disposeBUTTActionPerformed

    private void backBUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBUTTActionPerformed
        new inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBUTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dispatchWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dispatchWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dispatchWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dispatchWIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dispatchWIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBUTT;
    private javax.swing.JButton disposeBUTT;
    private javax.swing.JLabel incomeLABEL;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
